send_anonymous_usage_stats: false
Hackathon:
    target: Snowflake_DB
    outputs:
        Snowflake_DB:
            type: snowflake
            account: "JXGPFAR-REVOLT_PARTNER"
            user: "USER_09"
            password: "Veleska12"
            database: "HACKATHON"
            warehouse: "HACKATHON_WH"
            schema: "TEAM_09"

            
